"""Generate the proposed CAB contract from explicit models and operations (stdlib only)."""
import json
from pathlib import Path

S = {}
def ref(n): return {'$ref': '#/components/schemas/' + n}
def string(desc='', **kw): return dict(type='string', **({'description': desc} if desc else {}), **kw)
def enum(*v): return string(enum=list(v))
def num(desc='', **kw): return dict(type='number', description=desc, **kw)
def integer(desc='', **kw): return dict(type='integer', description=desc, **kw)
def arr(s): return {'type':'array', 'items': ref(s) if isinstance(s,str) else s}
def obj(props, required=()): return {'type':'object','properties':props, **({'required':list(required)} if required else {})}
def model(n,p,r=()): S[n]=obj(p,r); return ref(n)
ID=string('Mã định danh do server cấp.', example='trip_001')
DT=string('Thời gian RFC 3339, lưu UTC.',format='date-time',example='2026-09-07T03:00:00Z')
MONEY=integer('Số tiền nguyên, đơn vị VND.',minimum=0,example=65000)
VERSION=integer('Phiên bản tăng sau mỗi thay đổi; dùng chống ghi đè khi đồng bộ.',minimum=1,example=1)
S['VehicleType']=enum('MOTORBIKE','CAR_4','CAR_7')
S['PaymentMethod']=enum('CASH','BANK_CARD','E_WALLET')
S['TripStatus']=enum('SEARCHING','DRIVER_ASSIGNED','ARRIVED','PICKED_UP','IN_PROGRESS','COMPLETED','CANCELLED')
S['PaymentStatus']=enum('UNPAID','PENDING','PAID','FAILED','PARTIALLY_REFUNDED','REFUNDED')
model('Error',{'code':string('Mã lỗi máy đọc được.',example='INVALID_TRIP_STATE'),'message':string(example='Trạng thái chuyến không cho phép thao tác.'),'requestId':string(),'details':arr(obj({'field':string(),'message':string()},['field','message']))},['code','message','requestId'])
model('Point',{'latitude':num('Vĩ độ.',minimum=-90,maximum=90,example=10.822),'longitude':num('Kinh độ.',minimum=-180,maximum=180,example=106.688),'address':string('Địa chỉ hiển thị.',example='12 Nguyễn Văn Bảo, TP. Hồ Chí Minh')},['latitude','longitude'])
model('Location',{'point':ref('Point'),'recordedAt':DT,'accuracyMeters':num('Sai số GPS, mét.',minimum=0),'sequence':integer('Số thứ tự tăng trên thiết bị.',minimum=0)},['point','recordedAt','sequence'])
model('User',{'id':ID,'fullName':string(example='Nguyễn Văn An'),'phone':string(example='+84901234567'),'email':string(format='email',example='an@example.com'),'role':enum('CUSTOMER','DRIVER','OPERATOR','MANAGER','ADMIN'),'status':enum('ACTIVE','LOCKED'),'createdAt':DT},['id','fullName','phone','email','role','status','createdAt'])
model('ProfileUpdate',{'fullName':string(minLength=1),'email':string(format='email')})
model('VehicleInput',{'vehicleType':ref('VehicleType'),'plateNumber':string(minLength=1,example='59A-12345'),'brand':string(minLength=1),'model':string(minLength=1),'color':string(minLength=1),'documentIds':arr(ID)},['vehicleType','plateNumber','brand','model','color','documentIds'])
model('Vehicle',{'id':ID,'driverId':ID,**S['VehicleInput']['properties'],'reviewStatus':enum('PENDING','APPROVED','REJECTED'),'reviewReason':string(),'active':{'type':'boolean'}},['id','driverId','vehicleType','plateNumber','reviewStatus','active'])
model('DriverProfileInput',{'identityNumber':string('CCCD; dữ liệu riêng tư, chỉ chủ hồ sơ và nhân viên có quyền được đọc.',minLength=1),'licenseNumber':string(minLength=1),'documentIds':arr(ID)},['identityNumber','licenseNumber','documentIds'])
model('DriverProfile',{'user':ref('User'),**S['DriverProfileInput']['properties'],'reviewStatus':enum('PENDING','APPROVED','REJECTED'),'reviewReason':string(),'availability':enum('OFFLINE','AVAILABLE','BUSY'),'averageRating':num(minimum=1,maximum=5,nullable=True),'vehicle':ref('Vehicle')},['user','reviewStatus','availability'])
model('Registration',{'role':enum('CUSTOMER','DRIVER'),'fullName':string(minLength=1),'phone':string(minLength=1),'email':string(format='email'),'password':string('Chính sách độ dài/độ mạnh cần chốt trước triển khai.',minLength=1,writeOnly=True),'otpChannel':enum('SMS','EMAIL'),'driverProfile':ref('DriverProfileInput'),'vehicle':ref('VehicleInput')},['role','fullName','phone','email','password','otpChannel'])
S['Registration']['description']='DRIVER bắt buộc có driverProfile và vehicle; CUSTOMER không gửi hai trường này. Không cho tự đăng ký vai trò nội bộ.'
model('OtpChallenge',{'registrationId':ID,'expiresAt':DT,'resendAvailableAt':DT,'maskedDestination':string(example='a***@example.com'),'uploadToken':string('Token tạm chỉ được tải giấy tờ cho hồ sơ đăng ký này; không dùng gọi API nghiệp vụ.',readOnly=True)},['registrationId','expiresAt','resendAvailableAt','maskedDestination'])
model('OtpVerify',{'registrationId':ID,'otp':string('Mã OTP từ kênh đã chọn; không trả lại mã trong response.',minLength=1,writeOnly=True)},['registrationId','otp'])
model('Login',{'identifier':string('Số điện thoại hoặc email.',example='an@example.com'),'password':string(writeOnly=True,minLength=1)},['identifier','password'])
model('Session',{'accessToken':string(),'tokenType':enum('Bearer'),'expiresAt':DT,'user':ref('User')},['accessToken','tokenType','expiresAt','user'])
model('Document',{'id':ID,'fileName':string(),'mediaType':string(),'createdAt':DT},['id','fileName','mediaType','createdAt'])
model('RouteRequest',{'pickup':ref('Point'),'destination':ref('Point'),'vehicleType':ref('VehicleType')},['pickup','destination','vehicleType'])
model('Route',{'points':arr('Point'),'distanceMeters':num(minimum=0),'durationSeconds':integer(minimum=0)},['points','distanceMeters','durationSeconds'])
model('FareEstimateRequest',S['RouteRequest']['properties'],S['RouteRequest']['required'])
model('FareEstimate',{'id':ID,'route':ref('Route'),'amount':MONEY,'currency':enum('VND'),'expiresAt':DT,'pricingNote':string('Giá dự kiến; giá cuối tính theo hành trình thực tế.')},['id','route','amount','currency','expiresAt'])
model('TripCreate',{'pickup':ref('Point'),'destination':ref('Point'),'vehicleType':ref('VehicleType'),'paymentMethod':ref('PaymentMethod'),'estimateId':ID,'note':string('Ghi chú đón khách.')},['pickup','destination','vehicleType','paymentMethod','estimateId'])
model('DriverPublic',{'id':ID,'fullName':string(),'phone':string('Chỉ cung cấp cho khách của chuyến đang được phục vụ.'),'averageRating':num(minimum=1,maximum=5,nullable=True),'vehicleType':ref('VehicleType'),'plateNumber':string(),'brand':string(),'color':string()},['id','fullName','vehicleType','plateNumber'])
model('Trip',{'id':ID,'customerId':ID,'driver':ref('DriverPublic'),'pickup':ref('Point'),'destination':ref('Point'),'vehicleType':ref('VehicleType'),'status':ref('TripStatus'),'paymentStatus':ref('PaymentStatus'),'paymentMethod':ref('PaymentMethod'),'estimatedFare':MONEY,'finalFare':MONEY,'currency':enum('VND'),'version':VERSION,'createdAt':DT,'assignedAt':DT,'arrivedAt':DT,'pickedUpAt':DT,'startedAt':DT,'completedAt':DT,'cancelledAt':DT,'cancelReason':string(),'cancelCode':enum('CUSTOMER_CANCELLED','DRIVER_CANCELLED','NO_DRIVER_AVAILABLE','CUSTOMER_NO_SHOW','OPERATIONS_CANCELLED'),'cancelledBy':enum('CUSTOMER','DRIVER','SYSTEM','OPERATOR'),'ratingDeadline':DT,'replacementTripId':ID},['id','customerId','pickup','destination','vehicleType','status','paymentStatus','paymentMethod','estimatedFare','currency','version','createdAt'])
model('Tracking',{'trip':ref('Trip'),'driverLocation':ref('Location'),'locationStatus':enum('LIVE','STALE','UNAVAILABLE'),'etaSeconds':integer(minimum=0,nullable=True),'route':ref('Route'),'serverTime':DT,'warnings':arr(string())},['trip','locationStatus','serverTime','warnings'])
model('TripEvent',{'id':ID,'tripId':ID,'type':enum('CREATED','OFFERED','ASSIGNED','ARRIVED','PICKED_UP','STARTED','COMPLETED','CANCELLED','PAYMENT_UPDATED','INCIDENT_UPDATED'),'occurredAt':DT,'status':ref('TripStatus'),'description':string()},['id','tripId','type','occurredAt','description'])
model('Offer',{'id':ID,'tripId':ID,'pickup':ref('Point'),'destination':ref('Point'),'vehicleType':ref('VehicleType'),'estimatedFare':MONEY,'pickupDistanceMeters':num(minimum=0),'expiresAt':DT,'status':enum('PENDING','ACCEPTED','REJECTED','EXPIRED','REVOKED')},['id','tripId','pickup','destination','vehicleType','expiresAt','status'])
model('StatusChange',{'status':enum('ARRIVED','PICKED_UP','IN_PROGRESS','COMPLETED'),'expectedVersion':VERSION,'location':ref('Location'),'occurredAt':DT},['status','expectedVersion','location','occurredAt'])
model('CancelRequest',{'reason':string(minLength=1),'expectedVersion':VERSION,'customerNoShow':{'type':'boolean','default':False}},['reason','expectedVersion'])
model('Fare',{'tripId':ID,'distanceMeters':num(minimum=0),'durationSeconds':integer(minimum=0),'baseAmount':MONEY,'distanceAmount':MONEY,'otherAmount':MONEY,'discountAmount':MONEY,'totalAmount':MONEY,'currency':enum('VND'),'calculatedAt':DT,'pricingRuleVersion':string(),'paymentStatus':ref('PaymentStatus')},['tripId','distanceMeters','totalAmount','currency','calculatedAt','paymentStatus'])
model('PaymentCreate',{'method':ref('PaymentMethod')},['method'])
model('Payment',{'id':ID,'tripId':ID,'method':ref('PaymentMethod'),'status':enum('PENDING','SUCCEEDED','FAILED','CANCELLED'),'amount':MONEY,'currency':enum('VND'),'providerReference':string(),'checkoutUrl':string('URL mô phỏng do server tạo; không chứa thông tin thẻ.',format='uri'),'failureCode':string(),'createdAt':DT,'updatedAt':DT},['id','tripId','method','status','amount','currency','createdAt','updatedAt'])
model('PaymentCallback',{'eventId':ID,'paymentId':ID,'providerReference':string(),'status':enum('SUCCEEDED','FAILED'),'amount':MONEY,'currency':enum('VND'),'occurredAt':DT,'failureCode':string()},['eventId','paymentId','providerReference','status','amount','currency','occurredAt'])
model('RatingInput',{'stars':integer(minimum=1,maximum=5,example=5),'labels':arr(string()),'comment':string(),'negativeReasons':arr(string())},['stars'])
S['RatingInput']['description']='Điểm 1–2 phải có negativeReasons không rỗng; nhãn tham khảo từ /rating-options.'
model('Rating',{'id':ID,'tripId':ID,**S['RatingInput']['properties'],'flagged':{'type':'boolean'},'createdAt':DT},['id','tripId','stars','flagged','createdAt'])
model('Notification',{'id':ID,'type':enum('BOOKING_RECEIVED','DRIVER_ASSIGNED','DRIVER_ARRIVED','TRIP_COMPLETED','PAYMENT_SUCCEEDED','PAYMENT_FAILED','TRIP_OFFER','TRIP_CHANGED','NO_DRIVER_AVAILABLE','CASH_REMINDER','ACCOUNT_UPDATED','INCIDENT_RESOLVED'),'title':string(),'body':string(),'tripId':ID,'read':{'type':'boolean'},'createdAt':DT},['id','type','title','body','read','createdAt'])
model('IncidentInput',{'category':enum('VEHICLE_BREAKDOWN','ACCIDENT','PAYMENT_DISPUTE','PAYMENT_PENDING','GPS_LOST','ROUTE_DEVIATION','TECHNICAL','OTHER'),'description':string(minLength=1)},['category','description'])
model('Incident',{'id':ID,'tripId':ID,**S['IncidentInput']['properties'],'status':enum('OPEN','IN_PROGRESS','AWAITING_APPROVAL','RESOLVED'),'createdAt':DT,'resolution':string()},['id','tripId','category','description','status','createdAt'])
model('InterventionInput',{'action':enum('CANCEL_TRIP','REASSIGN','ADJUST_FARE','RECONCILE_PAYMENT','REFUND','RESOLVE'),'reason':string(minLength=1),'expectedTripVersion':VERSION,'newFare':MONEY,'refundAmount':MONEY,'paymentId':ID,'evidenceReference':string('Mã bằng chứng đối soát; không chứa dữ liệu thẻ.'),'customerWantsReplacement':{'type':'boolean'},'replacementPickup':ref('Point')},['action','reason','expectedTripVersion'])
S['InterventionInput']['description']='ADJUST_FARE cần newFare; REFUND cần paymentId và refundAmount > 0; RECONCILE_PAYMENT cần paymentId và evidenceReference; REASSIGN cần customerWantsReplacement=true và replacementPickup. Server kiểm tra quyền theo action. Không sửa trực tiếp trạng thái thanh toán bằng dữ liệu client.'
model('Intervention',{'id':ID,'incidentId':ID,'action':S['InterventionInput']['properties']['action'],'status':enum('PENDING_APPROVAL','APPROVED','REJECTED','EXECUTING','SUCCEEDED','FAILED'),'reason':string(),'requestedBy':ID,'approvedBy':ID,'createdAt':DT,'replacementTripId':ID,'refundId':ID,'failureCode':string()},['id','incidentId','action','status','reason','requestedBy','createdAt'])
model('Refund',{'id':ID,'paymentId':ID,'amount':MONEY,'currency':enum('VND'),'status':enum('PENDING','SUCCEEDED','FAILED'),'createdAt':DT},['id','paymentId','amount','currency','status','createdAt'])
model('ReviewInput',{'decision':enum('APPROVED','REJECTED'),'reason':string(minLength=1)},['decision','reason'])
model('AuditLog',{'id':ID,'actorId':ID,'action':string(),'resourceType':string(),'resourceId':ID,'reason':string(),'changes':arr(obj({'field':string(),'before':string('Giá trị đã che dữ liệu nhạy cảm.'),'after':string('Giá trị đã che dữ liệu nhạy cảm.')},['field'])),'createdAt':DT},['id','actorId','action','resourceType','resourceId','createdAt'])
model('ReportRow',{'period':string(),'regionId':ID,'driverId':ID,'totalTrips':integer(minimum=0),'completedTrips':integer(minimum=0),'cancelledTrips':integer(minimum=0),'customerCancellations':integer(minimum=0),'driverCancellations':integer(minimum=0),'systemCancellations':integer(minimum=0),'completionRate':num('completedTrips / totalTrips; 0 khi mẫu số bằng 0.',minimum=0,maximum=1),'cancellationRate':num('cancelledTrips / totalTrips; 0 khi mẫu số bằng 0.',minimum=0,maximum=1),'grossRevenue':MONEY,'refunds':MONEY,'commission':MONEY,'netRevenue':MONEY,'averageRating':num(minimum=1,maximum=5,nullable=True),'acceptedOffers':integer(minimum=0),'rejectedOffers':integer(minimum=0),'expiredOffers':integer(minimum=0)},['totalTrips','completedTrips','cancelledTrips','completionRate','cancellationRate','grossRevenue','refunds','commission','netRevenue'])
model('Report',{'from':string(format='date'),'to':string(format='date'),'timezone':string(example='Asia/Ho_Chi_Minh'),'currency':enum('VND'),'summary':ref('ReportRow'),'rows':arr('ReportRow'),'generatedAt':DT},['from','to','timezone','currency','summary','rows','generatedAt'])
model('ExportRequest',{'from':string(format='date'),'to':string(format='date'),'groupBy':enum('DAY','WEEK','MONTH','QUARTER'),'regionId':ID,'driverId':ID,'vehicleType':ref('VehicleType'),'format':enum('XLSX','PDF')},['from','to','groupBy','format'])
model('ExportJob',{'id':ID,'status':enum('PENDING','PROCESSING','COMPLETED','FAILED'),'format':enum('XLSX','PDF'),'createdAt':DT,'expiresAt':DT,'failureCode':string()},['id','status','format','createdAt'])
model('Permission',{'code':string(),'description':string()},['code','description'])
model('Role',{'id':ID,'name':string(),'permissions':arr('Permission')},['id','name','permissions'])
model('Region',{'id':ID,'name':string()},['id','name'])
model('VehicleService',{'code':ref('VehicleType'),'name':string(),'available':{'type':'boolean'}},['code','name','available'])
model('RatingOptions',{'positiveLabels':arr(string()),'negativeReasons':arr(string())},['positiveLabels','negativeReasons'])
model('AvailabilityInput',{'status':enum('OFFLINE','AVAILABLE')},['status'])
model('Availability',{'status':enum('OFFLINE','AVAILABLE','BUSY'),'updatedAt':DT},['status','updatedAt'])
model('AccountStatusInput',{'status':enum('ACTIVE','LOCKED'),'reason':string(minLength=1)},['status','reason'])
model('AdminUserCreate',{'role':enum('CUSTOMER','DRIVER'),'fullName':string(minLength=1),'phone':string(minLength=1),'email':string(format='email'),'driverProfile':ref('DriverProfileInput'),'vehicle':ref('VehicleInput')},['role','fullName','phone','email'])
S['AdminUserCreate']['description']='DRIVER cần driverProfile và vehicle. Tạo đăng ký chờ xác minh và gửi OTP; người dùng tự xác minh và đặt mật khẩu qua /auth/invitations/activate. Không trả mật khẩu tạm.'
model('InvitationActivate',{'registrationId':ID,'otp':string(writeOnly=True,minLength=1),'password':string(writeOnly=True,minLength=1)},['registrationId','otp','password'])

ERRORS={400:('BadRequest','Dữ liệu sai định dạng hoặc thiếu trường.','VALIDATION_ERROR'),401:('Unauthorized','Chưa xác thực hoặc thông tin xác thực hết hạn.','UNAUTHORIZED'),403:('Forbidden','Không đủ quyền, sai chủ sở hữu hoặc tài khoản bị khóa.','FORBIDDEN'),404:('NotFound','Không tìm thấy tài nguyên.','NOT_FOUND'),409:('Conflict','Xung đột trạng thái, phiên bản, dữ liệu trùng hoặc thao tác đã xử lý.','CONFLICT'),422:('Unprocessable','Dữ liệu đúng định dạng nhưng vi phạm điều kiện nghiệp vụ.','BUSINESS_RULE_VIOLATION'),429:('TooManyRequests','Vượt giới hạn yêu cầu/OTP. Thử lại theo Retry-After.','RATE_LIMITED'),500:('ServerError','Lỗi nội bộ; sử dụng requestId khi liên hệ hỗ trợ.','INTERNAL_ERROR'),503:('Unavailable','Dịch vụ phụ thuộc tạm không khả dụng.','SERVICE_UNAVAILABLE')}
RESP={}
for code,(name,desc,err) in ERRORS.items():
    RESP[name]={'description':desc,'content':{'application/json':{'schema':ref('Error'),'example':{'code':err,'message':desc,'requestId':'req_001'}}}}
RESP['TooManyRequests']['headers']={'Retry-After':{'description':'Thời gian chờ tính bằng giây.','schema':integer(minimum=1)}}
PATHS={}
def q(name,schema=None,required=False,description=''):
    return {'name':name,'in':'query','required':required,'description':description or name,'schema':schema or string()}
PAGE=[q('page',integer(minimum=1,default=1)),q('pageSize',integer(minimum=1,maximum=100,default=20))]
def paged(name):
    n=name+'Page'
    if n not in S: model(n,{'items':arr(name),'page':integer(minimum=1),'pageSize':integer(minimum=1,maximum=100),'total':integer(minimum=0)},['items','page','pageSize','total'])
    return n
def op(method,path,oid,title,tag,desc,response=None,body=None,status=200,roles=None,fr=(),uc=(),params=(),public=False,errors=(),idem=False):
    ps=[]
    import re
    for n in re.findall(r'\{([^}]+)\}',path): ps.append({'name':n,'in':'path','required':True,'description':'Mã định danh '+n,'schema':string(minLength=1),'example':n.replace('Id','_001')})
    ps+=list(params)
    if idem: ps.append({'$ref':'#/components/parameters/IdempotencyKey'})
    e={400,429,500}|set(errors)
    if not public: e|={401,403}
    if '{' in path: e.add(404)
    if method!='get': e|={409,422}
    responses={str(status):{'description': 'Xử lý thành công.' if status!=202 else 'Đã tiếp nhận; truy vấn tài nguyên trả về để theo dõi kết quả.'}}
    if response: responses[str(status)]['content']={'application/json':{'schema':ref(response)}}
    for c in sorted(e): responses[str(c)]={'$ref':'#/components/responses/'+ERRORS[c][0]}
    o={'tags':[tag],'summary':title,'operationId':oid,'description':desc,'responses':responses,'x-required-roles':roles or ['AUTHENTICATED'],'x-readme-fr':list(fr),'x-readme-use-cases':list(uc)}
    if ps:o['parameters']=ps
    if public:o['security']=[]; o['x-required-roles']=[]
    if body:o['requestBody']={'required':True,'content':{'application/json':{'schema':ref(body)}}}
    PATHS.setdefault(path,{})[method]=o
    return o

op('post','/auth/registrations','register','Đăng ký và gửi OTP','Auth','Tạo hồ sơ đăng ký tạm, kiểm tra trùng SĐT/email. Tài khoản chỉ được kích hoạt sau OTP. DRIVER gửi thông tin CCCD, bằng lái, xe; documentIds có thể rỗng lúc đăng ký, bổ sung giấy tờ sau xác minh. Hồ sơ chưa duyệt không được nhận chuyến. SMS/email dùng bộ mô phỏng trong đồ án, không SMS Brandname.', 'OtpChallenge','Registration',202,fr=['FR01.1','FR01.4','FR10.1'],uc=['UC002'],public=True,errors=[503])
op('post','/auth/registrations/verify','verifyRegistration','Xác minh OTP và tạo tài khoản','Auth','OTP sai/hết hạn trả 422 OTP_INVALID_OR_EXPIRED. OTP chỉ dùng một lần. Xác minh duy nhất SĐT/email một lần nữa trước khi tạo.', 'User','OtpVerify',201,fr=['FR01.1','FR10.1'],uc=['UC002'],public=True)
model('ResendOtp',{'registrationId':ID},['registrationId'])
op('post','/auth/registrations/resend-otp','resendOtp','Gửi lại OTP','Auth','Vô hiệu mã cũ; giới hạn gửi và lần thử theo cấu hình chưa chốt. Không trả OTP trong response.', 'OtpChallenge','ResendOtp',202,uc=['UC002'],public=True,errors=[503])
op('post','/auth/invitations/activate','activateInvitation','Kích hoạt tài khoản do vận hành tạo','Auth','Xác minh OTP và đặt mật khẩu của chính người dùng; áp dụng quy tắc hồ sơ tài xế như đăng ký công khai. Thiết kế hỗ trợ UC013.', 'User','InvitationActivate',201,uc=['UC013'],public=True)
op('post','/auth/login','login','Đăng nhập bằng SĐT/email và mật khẩu','Auth','Sai tài khoản/mật khẩu trả 401 INVALID_CREDENTIALS; tài khoản khóa trả 403 ACCOUNT_LOCKED. Token không chứa quyền do client tự khai báo.', 'Session','Login',fr=['FR01.2','FR10.1'],uc=['UC001'],public=True,errors=[401,403])
op('post','/auth/logout','logout','Đăng xuất','Auth','Thu hồi phiên hiện tại trên server.',status=204,fr=['FR10.1'])
op('get','/users/me','getMe','Xem hồ sơ cá nhân','Accounts','Chỉ dữ liệu của người gọi.', 'User',fr=['FR01.3'])
op('patch','/users/me','updateMe','Cập nhật thông tin cá nhân','Accounts','Không được sửa role/status. Email phải duy nhất. Việc đổi thông tin xác thực cần quy trình xác minh riêng trước triển khai; endpoint này chỉ đổi email liên hệ, không đổi định danh đăng nhập.', 'User','ProfileUpdate',fr=['FR01.3'])
for method in ['get','put']:
    op(method,'/drivers/me/profile',method+'DriverProfile','Xem hồ sơ tài xế' if method=='get' else 'Cập nhật hồ sơ tài xế','Drivers','Chỉ tài xế sở hữu. Thay đổi giấy tờ đưa hồ sơ về PENDING để duyệt lại. Dữ liệu nhạy cảm không xuất hiện trong thông tin tài xế công khai.', 'DriverProfile',None if method=='get' else 'DriverProfileInput',roles=['DRIVER'],fr=['FR01.4'])
    op(method,'/drivers/me/vehicle',method+'DriverVehicle','Xem phương tiện của tôi' if method=='get' else 'Đăng ký/cập nhật phương tiện','Drivers','Thiết kế mỗi tài xế một xe hoạt động. PUT tạo hoặc thay thế thông tin, biển số duy nhất; đổi xe/giấy tờ cần duyệt lại. Không đổi phương tiện khi đang thực hiện chuyến.', 'Vehicle',None if method=='get' else 'VehicleInput',roles=['DRIVER'],fr=['FR01.5'])
op('put','/drivers/me/availability','setAvailability','Bật/tắt nhận cuốc','Drivers','Chỉ hồ sơ và xe APPROVED mới bật AVAILABLE. BUSY do server quản lý; đang phục vụ chuyến không được tự giải phóng trạng thái.', 'Availability','AvailabilityInput',roles=['DRIVER'],fr=['FR03.1','FR08.6'])
op('post','/drivers/me/locations','recordLocation','Cập nhật vị trí GPS','Drivers','Lưu dấu vết theo recordedAt/sequence; mẫu cũ không ghi đè vị trí mới nhất. Server gắn vị trí vào chuyến đang được phân công. Không nhận driverId tùy ý.',status=204,body='Location',roles=['DRIVER'],fr=['FR03.1','FR03.2','FR04.7'])
o=op('post','/documents','uploadDocument','Tải giấy tờ hồ sơ/xe','Accounts','Chủ hồ sơ tải giấy tờ; chỉ nhận JPEG/PNG/PDF, kiểm tra nội dung tệp. Giới hạn dung lượng cần cấu hình. ID tài liệu phải thuộc người dùng khi gắn vào hồ sơ. Không trả URL công khai.', 'Document',status=201,roles=['CUSTOMER','DRIVER','OPERATOR'],fr=['FR01.4','FR01.5','FR08.3'])
o['requestBody']={'required':True,'content':{'multipart/form-data':{'schema':obj({'file':string(format='binary'),'kind':enum('IDENTITY','DRIVING_LICENSE','VEHICLE_REGISTRATION')},['file','kind'])}}}
o=op('get','/documents/{documentId}','downloadDocument','Đọc giấy tờ được cấp quyền','Accounts','Chỉ chủ tài liệu hoặc nhân viên có quyền documents:read. Kiểm tra quyền từng tài liệu; không cung cấp đường dẫn lưu trữ nội bộ.',roles=['DRIVER','OPERATOR','ADMIN'],fr=['FR01.4','FR08.2','FR08.3'])
o['responses']['200']['content']={m:{'schema':string(format='binary')} for m in ['application/pdf','image/jpeg','image/png']}
op('get','/vehicle-types','listVehicleTypes','Danh sách loại xe','Booking','Ba loại xe của UC003; khả dụng theo khu vực.',paged('VehicleService'),params=PAGE+[q('regionId')],fr=['FR02.3'],uc=['UC003'])
op('get','/regions','listRegions','Danh mục khu vực','Booking','Dùng chọn khu vực phục vụ và bộ lọc báo cáo.',paged('Region'),params=PAGE,uc=['UC016'])
op('get','/places','searchPlaces','Tìm địa chỉ/điểm đón và đến','Booking','Adapter bản đồ cơ bản hoặc mô phỏng. Không tích hợp định tuyến tránh kẹt xe có bản quyền.',paged('Point'),params=PAGE+[q('query',string(minLength=1),True)],fr=['FR02.1','FR02.2'],uc=['UC003'],errors=[503])
op('post','/routes','calculateRoute','Tính lộ trình dự kiến','Booking','Trả danh sách tọa độ để vẽ đường, khoảng cách và thời gian; địa chỉ không xác định trả 422 LOCATION_UNRESOLVABLE.', 'Route','RouteRequest',fr=['FR02.1','FR02.2'],uc=['UC003'],errors=[503])
op('post','/fare-estimates','estimateFare','Ước tính cước trước khi đặt','Booking','Bảng giá theo loại xe và quãng đường; công thức chưa chốt. Không dùng dynamic pricing. Báo giá gắn chủ sở hữu và bộ thông tin chuyến; thời hạn trả qua expiresAt.', 'FareEstimate','FareEstimateRequest',roles=['CUSTOMER'],fr=['FR05.2'],uc=['UC003'],errors=[503])
op('post','/trips','createTrip','Tạo yêu cầu đặt xe','Trips','Kiểm tra estimateId thuộc khách, chưa hết hạn và khớp điểm đón/đến/loại xe. Tạo SEARCHING và UNPAID; tự động chọn tài xế AVAILABLE phù hợp, ưu tiên khoảng cách/hiệu quả, gửi offer. 201 chỉ xác nhận tạo yêu cầu. Không tìm được tài xế: chuyển CANCELLED với cancelCode=NO_DRIVER_AVAILABLE, cancelledBy=SYSTEM và thông báo. Thời gian và trọng số chưa chốt.', 'Trip','TripCreate',201,roles=['CUSTOMER'],fr=['FR02.4','FR03.1','FR03.2','FR03.3','FR03.6','FR03.7','FR07.1','FR07.6'],uc=['UC003','UC004'],idem=True)
op('get','/trips','listMyTrips','Lịch sử chuyến của tôi','Trips','Khách chỉ thấy chuyến của mình; tài xế chỉ thấy chuyến đã được phân công. Không cho client truyền customerId để xem người khác.',paged('Trip'),roles=['CUSTOMER','DRIVER'],params=PAGE+[q('status',ref('TripStatus'))],fr=['FR02.5'],uc=['UC009','UC012'])
op('get','/trips/{tripId}','getTrip','Chi tiết và trạng thái yêu cầu','Trips','Chỉ khách sở hữu hoặc tài xế được phân công. Thanh toán tách paymentStatus; COMPLETED không đồng nghĩa PAID.', 'Trip',roles=['CUSTOMER','DRIVER'],fr=['FR02.5','FR04.6'],uc=['UC009'])
op('get','/trips/{tripId}/tracking','trackTrip','Theo dõi vị trí và ETA','Trips','Polling snapshot có thời gian server. Chỉ khách sở hữu/tài xế được phân công. Giữ vị trí cuối khi mất GPS và trả STALE/UNAVAILABLE; không dùng vị trí cũ như dữ liệu trực tiếp. Sau kết thúc ngừng lộ vị trí mới của tài xế, chỉ trả vị trí cuối thuộc chuyến. Chu kỳ polling/ngưỡng stale chưa chốt.', 'Tracking',roles=['CUSTOMER','DRIVER'],fr=['FR04.6','FR04.7'],uc=['UC009'])
op('get','/trips/{tripId}/events','listTripEvents','Lịch sử trạng thái chuyến','Trips','Chỉ người tham gia chuyến; sự kiện sắp xếp theo thời gian, không chứa audit nội bộ.',paged('TripEvent'),roles=['CUSTOMER','DRIVER'],params=PAGE,fr=['FR04.6'],uc=['UC009'])
op('get','/drivers/me/offers','listOffers','Danh sách lời mời nhận chuyến','Dispatch','Chỉ offer gửi tới tài xế hiện tại. expiresAt lấy từ server. Hết hạn được thu hồi tự động và chuyển tài xế khác; khách không tạo lại yêu cầu.',paged('Offer'),roles=['DRIVER'],params=PAGE+[q('status',S['Offer']['properties']['status'])],fr=['FR03.3','FR03.6'],uc=['UC004','UC006'])
op('post','/drivers/me/offers/{offerId}/accept','acceptOffer','Chấp nhận lời mời','Dispatch','Kiểm tra đồng thời offer còn hạn/PENDING, chuyến SEARCHING, tài xế AVAILABLE. Gán và chuyển BUSY nguyên tử; chuyến DRIVER_ASSIGNED. Offer hết hạn/bị thu hồi/chuyến đã hủy trả 409 OFFER_UNAVAILABLE. Gửi thông tin tài xế cho khách.', 'Trip',roles=['DRIVER'],fr=['FR03.4','FR04.1','FR07.2'],uc=['UC004','UC006','UC007'],idem=True)
model('Reason',{'reason':string(minLength=1)},['reason'])
op('post','/drivers/me/offers/{offerId}/reject','rejectOffer','Từ chối lời mời','Dispatch','Chỉ offer PENDING của mình. Ghi tỷ lệ từ chối, giữ AVAILABLE, tiếp tục tìm tài xế khác trên cùng tripId. Timeout tự động có kết quả tương tự; không cần API client kích hoạt timeout.', 'Offer','Reason',roles=['DRIVER'],fr=['FR03.5','FR03.6'],uc=['UC006','UC007'],idem=True)
op('post','/trips/{tripId}/status-transitions','transitionTrip','Cập nhật tiến trình/đồng bộ khi có mạng','Trips','Chỉ tài xế đang được phân công. Trình tự DRIVER_ASSIGNED → ARRIVED → PICKED_UP → IN_PROGRESS → COMPLETED. Nút Bắt đầu trong UC008 có thể gửi tuần tự PICKED_UP và IN_PROGRESS để lưu đủ FR04.3/FR04.4. ARRIVED kiểm tra GPS và ngưỡng khoảng cách chưa chốt (422 PICKUP_TOO_FAR). COMPLETED tự chốt cước từ dấu vết đã xác minh và gửi thông báo. Khi offline lưu request, gửi lại cùng Idempotency-Key; sai expectedVersion trả 409 VERSION_CONFLICT, đọc lại chuyến trước khi xử lý. Không chấp nhận thời gian tương lai hoặc trình tự sự kiện đảo ngược.', 'Trip','StatusChange',roles=['DRIVER'],fr=['FR04.2','FR04.3','FR04.4','FR04.5','FR05.1','FR05.2','FR07.3','FR07.4'],uc=['UC008'],idem=True)
op('post','/trips/{tripId}/cancel','cancelTrip','Hủy chuyến/hủy tìm kiếm/khách vắng mặt','Trips','Chỉ khách sở hữu hoặc tài xế được phân công. Thiết kế cho tự hủy ở SEARCHING, DRIVER_ASSIGNED, ARRIVED; đang chở khách cần vận hành xử lý sự cố. customerNoShow=true chỉ tài xế, trạng thái ARRIVED và hết thời gian chờ cấu hình. Ghi cancelCode/cancelledBy, thu hồi offer, giải phóng tài xế, gửi thông báo. Phí/chế tài hủy chưa chốt; không mặc định miễn phí.', 'Trip','CancelRequest',roles=['CUSTOMER','DRIVER'],fr=['FR07.7'],uc=['UC003','UC008','UC009'],idem=True)
op('get','/trips/{tripId}/fare','getFinalFare','Xem cước cuối và hóa đơn','Payments','Chỉ người tham gia chuyến. Cước được server tính khi kết thúc hoặc xử lý sự cố, chưa có trả 409 FARE_NOT_READY. Công thức chi tiết chưa chốt; client không gửi số tiền phải thu.', 'Fare',roles=['CUSTOMER','DRIVER'],fr=['FR05.1','FR05.2'],uc=['UC010'],errors=[409])
op('post','/trips/{tripId}/payments','createPayment','Khởi tạo thanh toán hoặc thanh toán lại','Payments','Chỉ khách sở hữu; chuyến đã có cước cuối. Lấy số tiền từ hóa đơn server. CASH tạo bản ghi PENDING chờ tài xế xác nhận; BANK_CARD/E_WALLET trả checkoutUrl mô phỏng. Chỉ tạo lần thử mới khi lần trước FAILED/CANCELLED; PENDING phải đối soát trước, PAID từ chối thu lại. Sau thất bại được đổi sang CASH theo chính sách. Timeout cổng giữ PENDING, tự truy vấn đối soát; không coi timeout là thất bại chắc chắn.', 'Payment','PaymentCreate',201,roles=['CUSTOMER'],fr=['FR06.1','FR06.2','FR06.5','FR06.6'],uc=['UC010','UC011'],idem=True,errors=[503])
op('get','/trips/{tripId}/payments','listTripPayments','Lịch sử giao dịch của chuyến','Payments','Chỉ khách sở hữu/tài xế được phân công; không chứa token hoặc dữ liệu thẻ.',paged('Payment'),roles=['CUSTOMER','DRIVER'],params=PAGE,fr=['FR06.6'],uc=['UC010','UC011'])
op('get','/payments/{paymentId}','getPayment','Tra cứu kết quả giao dịch','Payments','Chỉ người tham gia chuyến liên quan; dùng khi thanh toán PENDING hoặc vừa quay về từ checkout.', 'Payment',roles=['CUSTOMER','DRIVER'],fr=['FR06.3','FR06.6'],uc=['UC011'])
op('post','/payments/{paymentId}/confirm-cash','confirmCash','Tài xế xác nhận đã nhận tiền mặt','Payments','Chỉ tài xế được phân công, giao dịch CASH/PENDING và cước đã chốt. Server cập nhật SUCCEEDED và paymentStatus=PAID nguyên tử, gửi biên lai hai bên. Chưa xác nhận giữ PENDING, hệ thống gửi CASH_REMINDER; tranh chấp tạo incident. Không nhận số tiền tự khai báo.', 'Payment',roles=['DRIVER'],fr=['FR06.1','FR07.5'],uc=['UC010'],idem=True)
o=op('post','/integrations/payments/callback','paymentCallback','Nhận kết quả từ cổng thanh toán mô phỏng','Integrations','Endpoint server-to-server. Xác minh chữ ký trên raw body và timestamp, chống phát lại bằng eventId. Đối chiếu paymentId, providerReference, amount, currency; sai trả 422 PAYMENT_MISMATCH. Callback trùng hợp lệ trả 204, không thu/ghi doanh thu lần hai; kết quả mâu thuẫn giữ để đối soát, không hạ SUCCEEDED xuống FAILED. Signature algorithm, key rotation và cửa sổ timestamp cần chốt với adapter mô phỏng. Không tin kết quả redirect của trình duyệt.',body='PaymentCallback',status=204,public=True,fr=['FR06.3','FR06.4','FR06.6','FR07.5'],uc=['UC011'],errors=[401,403])
o['security']=[{'paymentSignature':[]}];o['x-required-roles']=['PAYMENT_PROVIDER'];o['parameters']=[{'name':'X-Payment-Timestamp','in':'header','required':True,'schema':DT,'description':'Thời điểm được bảo vệ bởi chữ ký.'}]
op('get','/rating-options','getRatingOptions','Nhãn đánh giá và lý do phản ánh','Ratings','Danh sách nhãn do server cấu hình.', 'RatingOptions',roles=['CUSTOMER'],uc=['UC012'])
op('post','/trips/{tripId}/rating','createRating','Đánh giá tài xế sau thanh toán','Ratings','Chỉ khách sở hữu; COMPLETED và PAID; mỗi chuyến một đánh giá, trong ratingDeadline (thời hạn chưa chốt). Điểm 1–2 yêu cầu negativeReasons và gắn cờ kiểm tra chất lượng. Cập nhật điểm trung bình tài xế.', 'Rating','RatingInput',201,roles=['CUSTOMER'],uc=['UC012'],idem=True)
op('get','/trips/{tripId}/rating','getRating','Xem đánh giá đã gửi','Ratings','Khách sở hữu hoặc tài xế của chuyến. Chưa đánh giá trả 404.', 'Rating',roles=['CUSTOMER','DRIVER'],uc=['UC012'])
op('get','/notifications','listNotifications','Hộp thông báo của tôi','Notifications','Thông báo tự sinh theo nghiệp vụ, không có API công khai gửi thông báo tùy ý cho người khác. Polling hỗ trợ nhận thay đổi và khi kết nối lại.',paged('Notification'),params=PAGE+[q('unreadOnly',{'type':'boolean','default':False})],fr=['FR07.'+str(i) for i in range(1,8)])
op('post','/notifications/{notificationId}/read','markNotificationRead','Đánh dấu đã đọc','Notifications','Chỉ thông báo của người gọi; gọi lại vẫn thành công.',status=204,fr=['FR07.7'])
model('DeviceInput',{'pushToken':string(writeOnly=True,minLength=1),'platform':enum('ANDROID','IOS','WEB')},['pushToken','platform'])
model('Device',{'id':ID,'platform':enum('ANDROID','IOS','WEB')},['id','platform'])
op('post','/devices','registerDevice','Đăng ký thiết bị nhận push','Notifications','Token gắn người gọi, không công khai. Adapter thông báo mô phỏng cho đồ án.', 'Device','DeviceInput',201,fr=['FR07.1','FR07.6'])
op('delete','/devices/{deviceId}','removeDevice','Hủy thiết bị nhận push','Notifications','Chỉ thiết bị của người gọi.',status=204)
op('post','/trips/{tripId}/incidents','reportIncident','Báo sự cố hoặc tranh chấp','Operations','Khách/tài xế liên quan chuyến tạo yêu cầu hỗ trợ; không được tự sửa doanh thu hoặc kết quả thanh toán.', 'Incident','IncidentInput',201,roles=['CUSTOMER','DRIVER'],fr=['FR08.7'],uc=['UC015'],idem=True)

ADMIN=['OPERATOR','ADMIN'];MANAGER=['MANAGER','ADMIN']
for resource,name,fr in [('users','User','FR08.1'),('drivers','DriverProfile','FR08.2'),('vehicles','Vehicle','FR08.3'),('trips','Trip','FR08.4')]:
    params=PAGE+[q('query',description='Tìm theo ID, tên, SĐT; phương tiện hỗ trợ biển số.'),q('regionId')]
    if resource=='users':params += [q('role',enum('CUSTOMER','DRIVER')),q('status',enum('ACTIVE','LOCKED')),q('plateNumber')]
    if resource=='drivers':params += [q('availability',enum('AVAILABLE','BUSY','OFFLINE')),q('reviewStatus',enum('PENDING','APPROVED','REJECTED'))]
    if resource=='vehicles':params += [q('driverId'),q('plateNumber'),q('reviewStatus',enum('PENDING','APPROVED','REJECTED'))]
    if resource=='trips':params += [q('status',ref('TripStatus')),q('activeOnly',{'type':'boolean'}),q('driverId'),q('customerId')]
    op('get','/admin/'+resource,'adminList'+resource.title(),'Tra cứu '+resource,'Administration','Yêu cầu quyền '+resource+':read; lọc và phân trang trên toàn hệ thống. Dữ liệu cá nhân chỉ cho nhân viên có quyền nghiệp vụ tương ứng.',paged(name),roles=ADMIN,params=params,fr=[fr]+(['FR08.6'] if resource=='drivers' else []),uc=['UC013'] if resource!='trips' else ['UC014'])
    singular={'users':'user','drivers':'driver','vehicles':'vehicle','trips':'trip'}[resource]
    op('get','/admin/'+resource+'/{'+singular+'Id}','adminGet'+resource.title(),'Chi tiết '+singular,'Administration','Yêu cầu quyền '+resource+':read; truy cập thông tin nhạy cảm được kiểm soát.',name,roles=ADMIN,fr=[fr],uc=['UC013'] if resource!='trips' else ['UC014'])
op('post','/admin/users','adminCreateUser','Vận hành tạo tài khoản khách/tài xế','Administration','Quyền users:write. Tạo lời mời, OTP gửi người dùng; DRIVER phải có hồ sơ và xe. Ghi audit. Không cho tạo ADMIN qua API này.', 'OtpChallenge','AdminUserCreate',202,roles=ADMIN,fr=['FR08.1','FR08.2'],uc=['UC013'])
op('patch','/admin/users/{userId}','adminUpdateUser','Cập nhật thông tin tài khoản','Administration','Quyền users:write; chỉ khách/tài xế, không đổi role/status qua body; kiểm tra email duy nhất và lưu audit.', 'User','ProfileUpdate',roles=ADMIN,fr=['FR08.1','FR08.2'],uc=['UC013'])
op('put','/admin/users/{userId}/status','adminSetUserStatus','Khóa/mở khóa tài khoản','Administration','Quyền users:lock. Khi khóa thu hồi mọi phiên, ngăn đăng nhập và nhận chuyến, thông báo lý do, lưu audit. Nếu đang có chuyến cần tạo incident để vận hành hỗ trợ; không tự bỏ qua việc xử lý khách đang trên xe.', 'User','AccountStatusInput',roles=ADMIN,fr=['FR08.1','FR08.2','FR10.1','FR10.3'],uc=['UC013'])
op('put','/admin/drivers/{driverId}/profile','adminUpdateDriverProfile','Cập nhật hồ sơ tài xế','Administration','Quyền drivers:write. Kiểm tra quyền tài liệu; thay đổi giấy tờ cần duyệt lại; lưu audit.', 'DriverProfile','DriverProfileInput',roles=ADMIN,fr=['FR08.2'],uc=['UC013'])
op('post','/admin/drivers/{driverId}/review','reviewDriver','Duyệt/từ chối hồ sơ tài xế','Administration','Quyền drivers:review; kiểm tra đủ giấy tờ trước APPROVED. Từ chối cần lý do và gửi thông báo. Duyệt đặc biệt cần quyền quản lý theo BR-09.', 'DriverProfile','ReviewInput',roles=ADMIN,fr=['FR08.2'],uc=['UC013'])
model('AdminVehicleCreate',{'driverId':ID,**S['VehicleInput']['properties']},['driverId']+S['VehicleInput']['required'])
op('post','/admin/vehicles','adminCreateVehicle','Tạo phương tiện cho tài xế','Administration','Quyền vehicles:write; biển số duy nhất, chủ là DRIVER; giấy tờ thuộc hồ sơ được quản lý; audit tự động.', 'Vehicle','AdminVehicleCreate',201,roles=ADMIN,fr=['FR08.3'],uc=['UC013'])
op('put','/admin/vehicles/{vehicleId}','adminUpdateVehicle','Cập nhật phương tiện','Administration','Quyền vehicles:write; không thay đổi xe đang phục vụ chuyến, không đổi chủ qua body. Kiểm tra trùng biển số và duyệt lại giấy tờ.', 'Vehicle','VehicleInput',roles=ADMIN,fr=['FR08.3'],uc=['UC013'])
op('post','/admin/vehicles/{vehicleId}/review','reviewVehicle','Duyệt/từ chối phương tiện','Administration','Quyền vehicles:review; ghi log và gửi thông báo cho tài xế. Không bao gồm kiểm định chuyên sâu.', 'Vehicle','ReviewInput',roles=ADMIN,fr=['FR08.3'],uc=['UC013'])
op('get','/admin/trips/{tripId}/tracking','adminTrackTrip','Giám sát vị trí chuyến trực tiếp','Operations','Quyền trips:monitor. Polling; cảnh báo mất GPS, lệch lộ trình, đứng yên lâu khi hệ thống phát hiện. Ngưỡng cảnh báo chưa chốt. Trả vị trí và thời gian cuối; không trình bày dữ liệu cũ là trực tiếp.', 'Tracking',roles=ADMIN,fr=['FR08.5'],uc=['UC014'])
op('get','/admin/trips/{tripId}/events','adminTripEvents','Lịch sử tiến trình phục vụ điều tra','Operations','Quyền trips:read; các thay đổi được ghi tự động.',paged('TripEvent'),roles=ADMIN,params=PAGE,fr=['FR08.7'],uc=['UC015'])
op('get','/admin/trips/{tripId}/locations','adminTripLocations','Tra cứu lộ trình đã đi','Operations','Quyền trips:monitor; chỉ mẫu GPS thuộc chuyến trong thời gian phục vụ. Thời hạn lưu trữ cần chốt.',paged('Location'),roles=ADMIN,params=PAGE,fr=['FR04.7','FR08.7'],uc=['UC015'])
op('get','/admin/payments','adminListPayments','Tra cứu giao dịch và đối soát','Payments','Quyền payments:read; lọc theo chuyến hoặc trạng thái để xử lý treo thanh toán.',paged('Payment'),roles=ADMIN,params=PAGE+[q('tripId'),q('status',S['Payment']['properties']['status'])],fr=['FR06.6','FR08.7'],uc=['UC015'])
op('get','/admin/payments/{paymentId}/refunds','adminListRefunds','Tra cứu kết quả hoàn tiền','Payments','Quyền payments:read; hoàn tiền được tạo qua can thiệp và phê duyệt, không cho gọi API hoàn tiền tùy ý.',paged('Refund'),roles=ADMIN,params=PAGE,uc=['UC015'])
op('get','/admin/incidents','listIncidents','Danh sách sự cố/chuyến lỗi','Operations','Quyền incidents:read. Hệ thống có thể tự tạo từ lỗi thanh toán, GPS hoặc cảnh báo; người dùng cũng báo sự cố.',paged('Incident'),roles=ADMIN,params=PAGE+[q('status',S['Incident']['properties']['status']),q('tripId')],fr=['FR08.7'],uc=['UC015'])
op('get','/admin/incidents/{incidentId}','getIncident','Chi tiết sự cố','Operations','Quyền incidents:read. Dùng tripId để truy vấn lịch sử trạng thái, GPS, thanh toán, audit.', 'Incident',roles=ADMIN,fr=['FR08.7'],uc=['UC015'])
op('post','/admin/trips/{tripId}/incidents','adminCreateIncident','Vận hành ghi nhận sự cố','Operations','Quyền incidents:write; phải nhập loại và nội dung, ghi audit.', 'Incident','IncidentInput',201,roles=ADMIN,fr=['FR08.7'],uc=['UC014','UC015'])
op('post','/admin/incidents/{incidentId}/interventions','requestIntervention','Yêu cầu can thiệp xử lý sự cố','Operations','Quyền incidents:write và quyền riêng theo action. Lưu yêu cầu trước; vượt thẩm quyền trả PENDING_APPROVAL và chưa thực thi. Hủy khẩn cấp chốt cước phần đã đi/miễn theo chính sách chưa chốt. REASSIGN hủy chuyến lỗi, tạo chuyến thay thế liên kết từ vị trí mới nếu khách đồng ý; không giả lập chuyến đang chở khách quay về SEARCHING. ADJUST_FARE chỉ hóa đơn chưa PAID và không có thanh toán PENDING; đã thu cần REFUND. REFUND không vượt số đã thu trừ hoàn trước, số tiền > 0. RECONCILE_PAYMENT phải kiểm chứng cổng, không tin trạng thái client. Khi thành công lưu audit và thông báo hai bên.', 'Intervention','InterventionInput',202,roles=ADMIN,fr=['FR08.7','FR10.2','FR10.3'],uc=['UC015'],idem=True)
op('get','/admin/interventions/{interventionId}','getIntervention','Theo dõi kết quả can thiệp','Operations','Quyền incidents:read; trả tiến trình thực thi/phê duyệt, lỗi và liên kết chuyến thay thế/hoàn tiền.', 'Intervention',roles=ADMIN+['MANAGER'],uc=['UC015'])
op('get','/admin/interventions','listInterventions','Hàng đợi phê duyệt can thiệp','Operations','Quyền incidents:read hoặc interventions:approve. Lọc PENDING_APPROVAL cho quản lý.',paged('Intervention'),roles=ADMIN+['MANAGER'],params=PAGE+[q('status',S['Intervention']['properties']['status'])],uc=['UC015'])
op('post','/admin/interventions/{interventionId}/decision','decideIntervention','Quản lý duyệt/từ chối can thiệp','Operations','Quyền interventions:approve và quyền tài chính phù hợp action. Chỉ PENDING_APPROVAL; người tạo không tự duyệt. Duyệt kích hoạt thực thi có kiểm tra lại phiên bản/số tiền; không tự đánh dấu thành công trước kết quả cổng. Ngưỡng hoàn tiền lớn/chính sách phê duyệt cần chốt.', 'Intervention','ReviewInput',202,roles=MANAGER,fr=['FR10.2','FR10.3'],uc=['UC015'],idem=True)
reportParams=[q('from',string(format='date'),True),q('to',string(format='date'),True),q('groupBy',enum('DAY','WEEK','MONTH','QUARTER')),q('regionId'),q('driverId'),q('vehicleType',ref('VehicleType'))]
op('get','/admin/reports/summary','reportSummary','Báo cáo chuyến, doanh thu, tỷ lệ và hiệu quả tài xế','Reports','Quyền reports:read; số liệu doanh thu cần reports:revenue. from/to bao gồm cả ngày theo Asia/Ho_Chi_Minh, from <= to. Đề xuất thống kê cohort theo createdAt chuyến, tổng hợp trạng thái tại generatedAt; doanh thu chỉ khoản đã thu của cohort trừ hoàn và chiết khấu. Hạch toán/chiết khấu chưa chốt; không tự áp tỷ lệ. Khi lọc driverId, chỉ tính chuyến đã gán tài xế đó. Không dữ liệu trả summary=0, rows=[], averageRating=null. Tỷ lệ trong [0,1], mẫu số 0 trả 0.', 'Report',roles=ADMIN+['MANAGER'],params=reportParams,fr=['FR09.'+str(i) for i in range(1,6)],uc=['UC016'],errors=[422])
op('post','/admin/reports/exports','createReportExport','Xuất báo cáo Excel/PDF','Reports','Cùng bộ lọc và quyền với summary; tạo job bất đồng bộ. Định dạng XLSX/PDF, không bao gồm BI nâng cao.', 'ExportJob','ExportRequest',202,roles=ADMIN+['MANAGER'],uc=['UC016'])
op('get','/admin/reports/exports/{exportId}','getReportExport','Theo dõi tiến trình xuất báo cáo','Reports','Chỉ người tạo hoặc người có quyền reports:export:read; kiểm tra lại quyền doanh thu.', 'ExportJob',roles=ADMIN+['MANAGER'],uc=['UC016'])
o=op('get','/admin/reports/exports/{exportId}/file','downloadReportExport','Tải báo cáo đã xuất','Reports','Quyền như job. Chỉ COMPLETED, chưa hết expiresAt; chưa sẵn sàng trả 409 EXPORT_NOT_READY, hết hạn trả 404. Content-Type phù hợp định dạng job.',roles=ADMIN+['MANAGER'],uc=['UC016'],errors=[409])
o['responses']['200']['content']={m:{'schema':string(format='binary')} for m in ['application/pdf','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet']}
o['responses']['200']['headers']={'Content-Disposition':{'schema':string(),'description':'attachment; filename="cab-report.xlsx" hoặc cab-report.pdf'}}
op('get','/users/me/permissions','getMyPermissions','Xem quyền hiện tại','Security','Quyền do server quyết định; UI dùng để hiển thị chức năng, backend vẫn kiểm tra mọi request.',paged('Permission'),params=PAGE,fr=['FR10.2'])
op('get','/admin/roles','listRoles','Danh mục vai trò và quyền','Security','Quyền roles:read. Vai trò và quyền được cấu hình khi triển khai; README không yêu cầu API tự cấp quyền quản trị.',paged('Role'),roles=MANAGER,params=PAGE,fr=['FR10.2'])
op('get','/admin/audit-logs','listAuditLogs','Tra cứu nhật ký kiểm toán','Security','Quyền audit:read. Nhật ký tự sinh, bất biến qua API, không có endpoint sửa/xóa. Che thông tin nhạy cảm, không lưu OTP/password/token/dữ liệu thẻ. from <= to; thời hạn lưu trữ chưa chốt.',paged('AuditLog'),roles=MANAGER,params=PAGE+[q('actorId'),q('resourceId'),q('action'),q('from',DT),q('to',DT)],fr=['FR10.3'],uc=['UC013','UC015'])

op('post','/notifications/{notificationId}/received','acknowledgeNotification','Xác nhận thiết bị đã nhận thông báo','Notifications','Chỉ thông báo của người gọi. Gọi lại không tạo bản ghi trùng; đánh dấu đã nhận độc lập với đã đọc.',status=204,uc=['UC005'])
S['Notification']['properties']['receivedAt']=DT
S['Notification']['properties']['readAt']=DT
S['Notification']['properties']['offerId']=ID
for path,method in [('/notifications','get'),('/notifications/{notificationId}/read','post'),('/devices','post'),('/drivers/me/offers','get')]:
    PATHS[path][method]['x-readme-use-cases'].append('UC005')
PATHS['/notifications']['get']['description']+=' UC005: lưu hàng đợi để gửi lại khi thiết bị có mạng; offer hết hạn không gửi lại lời mời đang hoạt động, tự chuyển tài xế tiếp theo. Gửi kênh chính lỗi thì ghi log và dùng kênh dự phòng mô phỏng cho tin quan trọng. Thiết bị xác nhận received/read qua API tương ứng; khi mở offer phải đọc lại trạng thái server.'
S['OtpChallenge']['properties'].pop('uploadToken',None)

DOC={'openapi':'3.0.3','info':{'title':'CAB System API','version':'0.1.0'},'servers':[{'url':'http://localhost:8080/api/v1','description':'Địa chỉ backend dự kiến; thay khi triển khai.'}],'security':[{'bearerAuth':[]}],'tags':[{'name':t,'description':d} for t,d in [('Auth','Đăng ký, OTP, đăng nhập và phiên'),('Accounts','Tài khoản và tài liệu riêng tư'),('Drivers','Hồ sơ, xe, sẵn sàng, GPS'),('Booking','Địa chỉ, lộ trình, loại xe, báo giá'),('Trips','Đặt và theo dõi chuyến'),('Dispatch','Nhận/từ chối lời mời'),('Payments','Cước, thanh toán, lịch sử và hoàn tiền'),('Integrations','Callback của adapter mô phỏng'),('Ratings','Đánh giá chất lượng'),('Notifications','Thông báo và thiết bị'),('Administration','Quản lý tài khoản và phương tiện'),('Operations','Giám sát, sự cố và phê duyệt'),('Reports','Báo cáo, xuất Excel/PDF'),('Security','Quyền và audit')]],'paths':PATHS,'components':{'securitySchemes':{'bearerAuth':{'type':'http','scheme':'bearer','description':'Access token do /auth/login cấp; không giả định JWT.'},'paymentSignature':{'type':'apiKey','in':'header','name':'X-Payment-Signature','description':'Chữ ký của adapter thanh toán trên raw body và X-Payment-Timestamp; chỉ khai báo header không thay thế kiểm tra mật mã.'}},'parameters':{'IdempotencyKey':{'name':'Idempotency-Key','in':'header','required':True,'description':'Khóa duy nhất cho một thao tác logic, phạm vi người gọi + method + path. Retry cùng key và body trả lại kết quả gốc kể cả phiên bản đã tăng; cùng key khác body trả 409 IDEMPOTENCY_CONFLICT. Server phải lưu kết quả nguyên tử với thay đổi nghiệp vụ. Thời hạn lưu khóa cần chốt trước triển khai.','schema':string(minLength=1,maxLength=128),'example':'cab-request-0001'}},'schemas':S,'responses':RESP},'x-readme-business-rules':{'BR-01':'Bearer và kiểm tra quyền mọi thao tác nghiệp vụ','BR-02':'createTrip tự ưu tiên GPS/AVAILABLE/hiệu quả','BR-03':'rejectOffer/timeout chuyển tiếp trên cùng tripId','BR-04':'CANCELLED + NO_DRIVER_AVAILABLE và thông báo','BR-05':'COMPLETED tự chốt cước server','BR-06':'Không nhận/lưu PAN, CVV, tài khoản ngân hàng','BR-07':'FAILED cho thử lại; PENDING phải đối soát','BR-08':'status-transitions kiểm soát thứ tự và phiên bản','BR-09':'Quyền riêng từng action, hàng đợi phê duyệt','BR-10':'Audit tự động, API chỉ đọc','BR-11':'Giới hạn đối tượng, HTTPS, che dữ liệu nhạy cảm'}}

# Keep all keys and values valid YAML without depending on a third-party emitter.
def scalar(v):
    return json.dumps(v,ensure_ascii=False)
def emit(v,indent=0):
    pad=' '*indent; lines=[]
    if isinstance(v,dict):
        if not v:return [pad+'{}']
        for k,x in v.items():
            key=scalar(k)
            if isinstance(x,(dict,list)) and x:lines.append(pad+key+':');lines+=emit(x,indent+2)
            else:lines.append(pad+key+': '+scalar(x))
    elif isinstance(v,list):
        for x in v:
            if isinstance(x,(dict,list)) and x:lines.append(pad+'-');lines+=emit(x,indent+2)
            else:lines.append(pad+'- '+scalar(x))
    return lines

if __name__=='__main__':
    out=Path(__file__).with_name('openapi.yaml')
    try:
        import yaml
        class Dumper(yaml.SafeDumper):
            def ignore_aliases(self,data): return True
        def represent_string(dumper,value):
            return dumper.represent_scalar('tag:yaml.org,2002:str',value,style='|' if '\n' in value else None)
        Dumper.add_representer(str,represent_string)
        rendered=yaml.dump(DOC,Dumper=Dumper,allow_unicode=True,sort_keys=False,width=110)
    except ImportError:
        rendered='\n'.join(emit(DOC))+'\n'
    out.write_text(rendered,encoding='utf-8')
    print(f'{out}: {len(PATHS)} paths, {sum(len(v) for v in PATHS.values())} operations, {len(S)} schemas')
